#!/bin/bash


Usage () { cat >&2 <<EOF
Usage: $0 <from_version> <to_version>
Make a patch from one version of Drupal to another
EOF
}


# URL for Drupal distributions
DRUPAL_DIST_URL_PREFIX='https://ftp.drupal.org/files/projects/'
# Extension for Drupal distribution files
DRUPAL_DIST_FILE_EXT=.tar.gz
# Drupal files that should be excluded
DISPOSABLES=(
  [6]='CHANGELOG.txt COPYRIGHT.txt INSTALL.mysql.txt INSTALL.pgsql.txt install.php INSTALL.txt LICENSE.txt MAINTAINERS.txt UPGRADE.txt'
  [7]='CHANGELOG.txt COPYRIGHT.txt INSTALL.mysql.txt INSTALL.pgsql.txt install.php INSTALL.sqlite.txt INSTALL.txt LICENSE.txt MAINTAINERS.txt README.txt UPGRADE.txt web.config'
)


set -e

if [ $# -ne 2 ] ; then
  Usage
  exit 1
fi

for version ; do
  if ! [[ "$version" =~ ^[0-9]+\.[0-9]+$ ]] ; then
    Usage
    exit 1
  fi
done


Error () {
  echo >&2 "ERROR: $@"
}


download_drupal_dist () {
  local version=$1
  local dist_file_name=drupal-${version}${DRUPAL_DIST_FILE_EXT}
  local dist_url=${DRUPAL_DIST_URL_PREFIX}${dist_file_name}

  if ! [ -f "$dist_file_name" ] ; then
    wget \
      --verbose \
      --timestamping \
      --timeout=300 \
      "$dist_url"
  fi

  printf '%s\n' "$dist_file_name"
}


extract_drupal_dist () {
  local dist_file_name=$1
  local extracted_path=$( basename "$dist_file_name" ${DRUPAL_DIST_FILE_EXT} )

  if [ -d "$extracted_path" ] ; then
    echo >&2 "Error: Extracted copy already exists? '$extracted_path'"
    exit 2
  fi

  tar xf "$dist_file_name"

  printf '%s\n' "$extracted_path"
}


from_version=$1
to_version=$2

major_version=${from_version%%.*}
if ! [ "$major_version" = "${to_version%%.*}" ] ; then
  Error "Mismatched major versions: $from_version -> $to_version"
  exit 2
fi

patch_file_name=upgrade_drupal-${from_version}-${to_version}.patch

from_dist=$( download_drupal_dist "$from_version" )
to_dist=$( download_drupal_dist "$to_version" )

from_extracted=$( extract_drupal_dist "$from_dist" )
to_extracted=$( extract_drupal_dist "$to_dist" )

for extracted in "$from_extracted" "$to_extracted" ; do
  ( cd "$extracted" && rm ${DISPOSABLES[$major_version]} )
done

diff -ru "$from_extracted" "$to_extracted" > "$patch_file_name"
printf '%s\n' "$patch_file_name"
